# Generated by Django 3.2.16 on 2023-03-14 13:57

from django.db import migrations
import twitter_app.manager


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0003_user_img'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', twitter_app.manager.CustomeManagers()),
            ],
        ),
    ]
