# Generated by Django 3.2.16 on 2023-03-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0007_auto_20230316_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Dob',
        ),
    ]
