# Generated by Django 3.2.16 on 2023-03-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0008_remove_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
