# Generated by Django 3.2.16 on 2023-03-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0010_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
