# Generated by Django 3.2.16 on 2023-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0011_alter_tweet_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
