# Generated by Django 3.2.16 on 2023-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0012_alter_tweet_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(default='Post', null=True, upload_to=''),
        ),
    ]
