# Generated by Django 3.2.16 on 2023-03-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0013_alter_tweet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(blank=True, default='Post', null=True, upload_to=''),
        ),
    ]
