# Generated by Django 3.2.16 on 2023-03-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0020_alter_tweet_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='liked',
        ),
    ]
