# Generated by Django 3.2.16 on 2023-03-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0024_auto_20230331_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retweet',
            name='value',
            field=models.CharField(choices=[('ReTweet', 'Tweeted'), ('Retweeted', 'Retweeted')], default='Like', max_length=20),
        ),
    ]
