# Generated by Django 3.2.16 on 2023-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0026_auto_20230425_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
